//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amicitia.github.io.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amicitia.github.io.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;&lt;center&gt;&lt;a href=&quot;https://www.youtube.com/watch?v=FZ0cqpXL9EE&amp;amp;list=PLU6By7bu-RSvtk9aDlYplr73lfwpT2fFM&amp;amp;index=1&quot;&gt;&lt;img src=&quot;https://amicitia.github.io/images/404.jpg&quot;&gt;&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;&lt;a href=&quot;https://amicitia.github.io/&quot;&gt;Go Back&lt;/a&gt;&lt;/b&gt;&lt;/center&gt;.
        /// </summary>
        public static string _404 {
            get {
                return ResourceManager.GetString("_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Compiling&lt;/h1&gt;
        ///&lt;br&gt;Using &lt;b&gt;AtlusScriptCompiler&lt;/b&gt;, you can turn &lt;b&gt;.flow&lt;/b&gt; files into &lt;b&gt;.bf&lt;/b&gt; files, or &lt;b&gt;.msg&lt;/b&gt; files into &lt;b&gt;.bmd&lt;/b&gt; files. Anything else referenced in a .flow (bf/bmd/flow/msg) also becomes part of a resulting .bf file.
        ///&lt;br /&gt;
        ///&lt;br /&gt;You can &lt;a href=&quot;https://shrinefox.com?tool=atlusscriptcompiler&quot;&gt;download the latest AtlusScriptCompiler here&lt;/a&gt;.
        ///&lt;h2&gt;Using Commandline Arguments&lt;/h2&gt;
        ///Once you have extracted the program to a folder, simply clicking on the exe causes a con [rest of string was truncated]&quot;;.
        /// </summary>
        public static string compiling {
            get {
                return ResourceManager.GetString("compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Decompiling&lt;/h1&gt;&lt;br&gt;Using &lt;b&gt;AtlusScriptCompiler&lt;/b&gt;, you can turn &lt;b&gt;.bf&lt;/b&gt; files into &lt;b&gt;.flow&lt;/b&gt; files, or &lt;b&gt;.bmd&lt;/b&gt; files into &lt;b&gt;.msg&lt;/b&gt; files. Any .bmd contained in a .bf will also be automatically decompiled and output as a .msg file.
        ///						&lt;br /&gt;&lt;br /&gt;You can &lt;a href=&quot;https://shrinefox.com?tool=atlusscriptcompiler&quot;&gt;download the latest AtlusScriptCompiler here&lt;/a&gt;.
        ///						&lt;h2&gt;Using Commandline Arguments&lt;/h2&gt;
        ///						Once you have extracted the program to a folder, simply clicking on the exe  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string decompiling {
            get {
                return ResourceManager.GetString("decompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;
        ///&lt;br&gt;If you need dumped CPK or CVM contents for modding purposes,
        ///&lt;br&gt;check the links below to download what you need.
        ///&lt;br&gt;
        ///&lt;br&gt;&lt;b&gt;NOTE:&lt;/b&gt; Files necessary to actually run the games are &lt;b&gt;not included&lt;/b&gt;.
        ///&lt;br&gt;These are provided for research and development purposes only.
        ///&lt;br&gt;
        ///&lt;br&gt;Some links were removed from this page because the files are no longer available.
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;center&gt;&lt;h1&gt;Persona&lt;/h1&gt;&lt;/center&gt;
        ///&lt;hr&gt;
        ///&lt;br&gt;
        ///&lt;table&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr style=&quot;opacity:0.5;&quot;&gt;
        ///            &lt;td&gt;&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Flowscript&lt;/h1&gt;
        ///&lt;br&gt;&lt;b&gt;Flowscript&lt;/b&gt; is a scripting language created by &lt;b&gt;TGEnigma&lt;/b&gt; for use with his &lt;a href=&quot;https://shrinefox.com/?tool=atlusscriptcompiler&quot;&gt;AtlusScriptCompiler&lt;/a&gt;. It is the decompiled form of &lt;b&gt;BF&lt;/b&gt;, the binary output of Atlus&apos;s scripts which many of their games use to perform various logical procedures.
        ///&lt;br&gt;
        ///&lt;h2&gt;Decompiling&lt;/h2&gt;
        ///						You can convert &lt;b&gt;.BF&lt;/b&gt; to &lt;b&gt;.FLOW&lt;/b&gt; and open it with your text editor of choice &lt;a href=&quot;https://amicitia.github.io/docs/decompili [rest of string was truncated]&quot;;.
        /// </summary>
        public static string flowscript {
            get {
                return ResourceManager.GetString("flowscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * The template for displaying the footer
        /// *
        /// * Contains the closing of the #content div and all content after.
        /// *
        /// * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
        /// *
        /// * @package Justread
        /// */
        ///
        ///?&gt;
        ///
        ///	&lt;/div&gt;&lt;!-- #content --&gt;
        ///			&lt;!--INDEXFOOTER--&gt;.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**
        /// * The header for our theme
        /// *
        /// * This is the template that displays all of the &lt;head&gt; section and everything up until &lt;div id=&quot;content&quot;&gt;
        /// *
        /// * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
        /// *
        /// * @package Justread
        /// */
        ///
        ///?&gt;
        ///&lt;!doctype html&gt;
        ///&lt;html class=&quot;no-js&quot; &lt;?php language_attributes(); ?&gt;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;&lt;?php bloginfo( &apos;charset&apos; ); ?&gt;&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///	&lt;link rel=&quot;profile&quot; href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Hooking Functions&lt;/h1&gt;
        ///						AtlusScriptCompiler is not perfect, and sometimes decompiled data is imprecise (usually float values). This can lead to glitches (weird camera/player positioning and movement) and even crashes in-game when a recompiled script is modded back in.
        ///&lt;br /&gt;To get around this, AtlusScriptCompiler has a feature that preserves the original .BF&apos;s data, appending only new data to the end from your compiled .FLOW.
        ///&lt;br /&gt;You can use this to &lt;b&gt;replace the contents of a specific method [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hookingfunctions {
            get {
                return ResourceManager.GetString("hookingfunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Importing&lt;/h1&gt;
        ///						As seen in the &lt;a href=&quot;https://amicitia.github.io/docs/messagescript&quot;&gt;Messagescript&lt;/a&gt; tutorial, in order to use text strings in a .flow, you must reference a .msg file to get the strings from.
        ///&lt;br /&gt;An &quot;import statement&quot; usually looks like the following, at the top of the document:
        ///&lt;br /&gt;&lt;pre&gt;&lt;code&gt;import( &quot;field.msg&quot; );&lt;/code&gt;&lt;/pre&gt;
        ///&lt;br /&gt;The paths are relative to the .flow file, so in this case, if your .flow is at &lt;b&gt;C:\Users\Username\Documents\field.flow&lt;/b&gt;, it would loo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string importing {
            get {
                return ResourceManager.GetString("importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;background: linear-gradient(120deg, var(--gradient1) 0%, var(--gradient2) 100%) fixed;&quot;&gt;
        ///    &lt;!--Copied Message--&gt;
        ///    &lt;div class=&quot;copied&quot;&gt;Copied to Clipboard&lt;/div&gt;
        ///    &lt;div class=&quot;flex&quot;&gt;
        ///        &lt;!--TopRow--&gt;
        ///        &lt;div class=&quot;row top&quot;&gt;
        ///            &lt;!--Navbar--&gt;
        ///            &lt;div class=&quot;navbar&quot;&gt;
        ///                &lt;input type=&quot;checkbox&quot; id=&quot;css3menu-switcher&quot; class=&quot;c3m-switch-input&quot;&gt;
        ///                &lt;ul id=&quot;css3menu0&quot; class=&quot;topmenu&quot;&gt;
        ///                    &lt;li class=&quot;switch&quot;&gt;&lt;label oncl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexAfterHeader {
            get {
                return ResourceManager.GetString("IndexAfterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;!--Waves--&gt;
        ///    &lt;svg class=&quot;waves&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; viewBox=&quot;0 24 150 28&quot; preserveAspectRatio=&quot;none&quot; shape-rendering=&quot;auto&quot;&gt;
        ///        &lt;defs&gt;
        ///            &lt;path id=&quot;gentle-wave&quot; d=&quot;M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z&quot;&gt;&lt;/path&gt;
        ///        &lt;/defs&gt;
        ///        &lt;g class=&quot;parallax&quot;&gt;
        ///            &lt;use xlink:href=&quot;#gentle-wave&quot; x=&quot;48&quot; y=&quot;0&quot;&gt;&lt;/use&gt;
        ///            &lt;use xlink:href=&quot;#gentle-wave&quot; x=&quot;48&quot; y=&quot;3&quot;&gt;&lt;/use&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexBeforeContent {
            get {
                return ResourceManager.GetString("IndexBeforeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;link rel=&apos;shortcut icon&apos; href=&apos;https://amicitia.github.io/images/favicon.png&apos; type=&apos;image/x-icon&apos; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;.
        /// </summary>
        public static string IndexBeforeHeader {
            get {
                return ResourceManager.GetString("IndexBeforeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 								&lt;!--Pagination--&gt;
        ///                                &lt;/td&gt;
        ///							&lt;/tr&gt;
        ///						&lt;/table&gt;
        ///					&lt;/div&gt;
        ///                &lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;
        ///                &lt;!--Footer--&gt;
        ///                &lt;div class=&quot;row bottom&quot;&gt;
        ///                    &lt;footer&gt;
        ///                        &lt;table style=&quot;padding-right: 2%;&quot;&gt;
        ///                            &lt;tbody&gt;
        ///                                &lt;tr&gt;
        ///                                    &lt;td id=&quot;about_site&quot; style=&quot;vertical-align: top;width: 25%;&quot;&gt;
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexFooter {
            get {
                return ResourceManager.GetString("IndexFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://amicitia.github.io/js/jquery-3.3.1.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Lato:wght@300;400&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;script src=&quot;https://kit.fontawesome.com/4c3075832a.js&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
        ///&lt;script data-ad-client=&quot;ca-pub-9519592525056753&quot; async src=&quot;https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js&quot;&gt;&lt;/script&gt;
        ///&lt;link href=&quot;https://amicitia.github.io/favicon.ico&quot; rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; /&gt;
        ///&lt;link href= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 				&lt;/td&gt;
        ///				&lt;!--Sidebar--&gt;
        ///                &lt;td style=&quot;vertical-align:top;width:20%;text-align:right;font-size:10pt;&quot; class=&quot;bloglinks&quot;&gt;
        ///					&lt;b&gt;LATEST UPDATES&lt;/b&gt;
        ///                    &lt;div id=&quot;news-feed&quot;&gt;&lt;/div&gt;
        ///                    &lt;div id=&quot;guides-feed&quot;&gt;&lt;/div&gt;
        ///                    &lt;div id=&quot;blog-feed&quot;&gt;&lt;/div&gt;
        ///                    &lt;script&gt;
        ///						$(&apos;#news-feed&apos;).FeedEk({
        ///							FeedUrl:&apos;https://shrinefox.com/news/feed&apos;,
        ///							MaxCount : 3,
        ///							ShowDesc : false,
        ///							ShowPubDate:true,
        ///							Des [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexSidebar {
            get {
                return ResourceManager.GetString("IndexSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IF S_NOTIFICATIONS_DISPLAY --&gt;
        ///&lt;li&gt;
        ///	&lt;a href=&quot;https://shrinefox.com/forum/ucp.php?i=ucp_notifications&quot;&gt;
        ///		&lt;div class=&quot;item&quot;&gt;
        ///			&lt;i class=&quot;icon fa-bell fa-fw&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;&amp;nbsp;{L_NOTIFICATIONS}&lt;strong id=&quot;navtoggle&quot; class=&quot;badge&lt;!-- IF not NOTIFICATIONS_COUNT --&gt; hidden&lt;!-- ENDIF --&gt;&quot;&gt;{NOTIFICATIONS_COUNT}&lt;/strong&gt;
        ///		&lt;/div&gt;
        ///	&lt;/a&gt;
        ///&lt;/li&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;!-- IF U_ACP --&gt;
        ///&lt;li&gt;
        ///	&lt;a href=&quot;{U_ACP}&quot; title=&quot;{L_ACP}&quot; role=&quot;menuitem&quot;&gt;
        ///		&lt;div class=&quot;item&quot;&gt;
        ///			&lt;i class=&quot;icon fa-cogs fa-fw&quot; a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoginAndNotifications {
            get {
                return ResourceManager.GetString("LoginAndNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Messagescript&lt;/h1&gt;&lt;i&gt;Flowscript&lt;/i&gt; doesn&apos;t support &lt;a href=&quot;https://techterms.com/definition/string&quot;&gt;strings&lt;/a&gt; as a variable type, but it&apos;s possible to display text in the form of dialog and selectable options by referencing a &lt;b&gt;messagescript&lt;/b&gt; file.
        ///&lt;h2&gt;Creating a Messagescript&lt;/h2&gt;
        ///						Messagescripts are text files ending with the extension .&lt;b&gt;msg&lt;/b&gt;, often accompanying a .&lt;i&gt;flow&lt;/i&gt; (&lt;i&gt;flowscript&lt;/i&gt;). Simply create a new text file and rename the extension. You may need to &lt;a href=&quot;http [rest of string was truncated]&quot;;.
        /// </summary>
        public static string messagescript {
            get {
                return ResourceManager.GetString("messagescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;wrap&quot;&gt;
        ///    &lt;table id=&quot;wrap&quot; style=&quot;width: 150%;&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td style=&quot;width: 100%; display: inline-flex;&quot;&gt;
        ///                    Game: 
        ///                    &lt;select id=&quot;game&quot; name=&quot;game&quot; onchange=&quot;navigate()&quot; style=&quot;width: 50%;flex-grow: 100;&quot;&gt;
        ///                        &lt;option value=&quot;All&quot;&gt;&lt;/option&gt;
        ///                        &lt;option value=&quot;p5&quot;&gt;Persona 5&lt;/option&gt;
        ///                        &lt;option value=&quot;p5r&quot;&gt;Persona 5 Royal&lt;/option&gt;
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE config.html --&gt;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;{S_CONTENT_DIRECTION}&quot; lang=&quot;{S_USER_LANG}&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///{META}
        ///&lt;title&gt;&lt;!-- IF UNREAD_NOTIFICATIONS_COUNT --&gt;({UNREAD_NOTIFICATIONS_COUNT}) &lt;!-- ENDIF --&gt;&lt;!-- IF not S_VIEWTOPIC and not S_VIEWFORUM --&gt;{SITENAME} - &lt;!-- ENDIF --&gt;&lt;!-- IF S_IN_MCP --&gt;{L_MCP} - &lt;!-- ELSEIF S_IN_UCP --&gt;{L_UCP} - &lt;!-- ENDIF --&gt;{PAGE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string overall_header {
            get {
                return ResourceManager.GetString("overall_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;toggle&quot;&gt;
        ///    &lt;div class=&quot;toggle-title&quot;&gt;
        ///        &lt;table cellspacing=&quot;0&quot;&gt;
        ///            &lt;tr class=&quot;post&quot;&gt;
        ///                &lt;td&gt;
        ///                    POSTEMBED
        ///                &lt;/td&gt;
        ///                &lt;td&gt;
        ///                    &lt;b&gt;POSTTITLE&lt;/b&gt;
        ///                &lt;/td&gt;
        ///                &lt;td&gt;
        ///                    POSTTYPE
        ///                &lt;/td&gt;
        ///                &lt;td&gt;
        ///                    POSTAUTHORS
        ///                &lt;/td&gt;
        ///                &lt;td&gt;
        ///                    POSTDATE
        ///                &lt;/td&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--Result Count and Submission Link--&gt;
        ///&lt;table style=&quot;padding: 0 20px 0 15px;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td width=&quot;25%&quot;&gt;Page 0/0 (0 results)&lt;/td&gt;
        ///            &lt;td width=&quot;50%&quot; style=&quot;text-align: right;&quot;&gt;
        ///                &lt;a href=&quot;https://shrinefox.com/forum/viewtopic.php?f=4&amp;amp;t=682&amp;amp;p=2649#p2649&quot;&gt;
        ///                    &lt;i class=&quot;fa fa-upload&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; How to Submit
        ///                &lt;/a&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;
        ///&lt;!--Pagination--&gt;
        ///&lt;br&gt;
        ///&lt;! [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PostTableHeader {
            get {
                return ResourceManager.GetString("PostTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;td width=&quot;25%&quot; style=&quot;vertical-align:top&quot;&gt;
        ///            Basics
        ///            &lt;br&gt;↳ &lt;a href=&quot;https://amicitia.github.io/docs/flowscript&quot;&gt;Flowscript&lt;/a&gt;
        ///            &lt;br&gt;↳ &lt;a href=&quot;https://amicitia.github.io/docs/messagescript&quot;&gt;Messagescript&lt;/a&gt;
        ///            &lt;br&gt;↳ &lt;a href=&quot;https://amicitia.github.io/docs/decompiling&quot;&gt;Decompiling&lt;/a&gt;
        ///            &lt;br&gt;↳ &lt;a href=&quot;https://amicitia.github.io/docs/compiling&quot;&gt;Compiling&lt;/a&gt;
        ///            &lt;br&gt;
        ///            &lt;br&gt;Features
        ///            &lt;br&gt;↳ &lt;a h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string toc {
            get {
                return ResourceManager.GetString("toc", resourceCulture);
            }
        }
    }
}
